--- 
- name: Download Wordpress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz sha256sum="{{} wp_sha256sum }"
- name: Extract archive
  command: chdir = /srv/ tar xvf wordpress-{{ wp_version }}.tar.gz  creates=/srv/wordpress